### ISSUE TITLE
How to install on Capacitor 3.x ?

### ISSUE THREAD

**Issue by Saqib92** [capawesome-team/capacitor-screen-orientation#25]
is there older version available to install on capacitor v3.x or should i use cordova one?

**Comment by robingenz** [comment]
Version 1.1.7 of this plugin supports Capacitor 3 (see CHANGELOG.md).

**Comment by Saqib92** [comment]
showing error when installing v1.1.7. 
`npm install @capawesome/capacitor-screen-orientation@1.1.7`

error:
>No matching version found for @capawesome/capacitor-screen-orientation@1.1.7

**Comment by robingenz** [comment]
> This plugin was renamed to @capawesome/capacitor-screen-orientation. Please install the new npm package and run npx cap sync.

You need to install '@robingenz/capacitor-screen-orientation@1.1.7'.

**Comment by Saqib92** [comment]
> 

Thanks. It Worked.
