### ISSUE TITLE
bug: iOS 16.2 bug in client of UIKIT

### ISSUE THREAD

**Issue by Maartenb111** [capawesome-team/capacitor-screen-orientation#27]
**Plugin version:**

2.0.1

**Platform(s):**

iOS 16.2 

**Current behavior:**

**Plugin is working** but throws the following error message:

[Orientation] BUG IN CLIENT OF UIKIT: Setting UIDevice.orientation is not supported. Please use UIWindowScene.requestGeometryUpdate(_:)

**Expected behavior:**

No error thrown by plugin

**Steps to reproduce:**

Any Capacitor iOS app will do, just call ScreenOrientation.lock(...)

**Related code:**

None

**Other information:**

None

**Capacitor doctor:**

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/ios: 4.3.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

**Comment by robingenz** [comment]
Please fill out the issue template correctly so that i have all necessary information for reproduction.

**Comment by Maartenb111** [comment]
Sorry, I edited my initial post. Thanks
