### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by axi** [capawesome-team/capacitor-screen-orientation#30]
**Plugin version:**
2.0.2

**Platform(s):**
iOS Build

**Current behavior:**
Build errors:

```
node_modules/@capawesome/capacitor-screen-orientation/ios/Plugin/ScreenOrientation.swift:62:57: value of type 'UIViewController' has no member 'setNeedsUpdateOfSupportedInterfaceOrientations'
windowScene?.keyWindow?.rootViewController?.setNeedsUpdateOfSupportedInterfaceOrientations()

node_modules/@capawesome/capacitor-screen-orientation/ios/Plugin/ScreenOrientation.swift:63:26: value of type 'UIWindowScene' has no member 'requestGeometryUpdate'
windowScene?.requestGeometryUpdate(.iOS(interfaceOrientations: orientationMask))

node_modules/@capawesome/capacitor-screen-orientation/ios/Plugin/ScreenOrientation.swift:63:49: cannot infer contextual base in reference to member 'iOS'
windowScene?.requestGeometryUpdate(.iOS(interfaceOrientations: orientationMask)) 
```

**Expected behavior:**
Build successfull

**Other information:**
Reverting to 2.0.1 builds fine

**Capacitor doctor:**
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/android: 4.7.0
  @capacitor/ios: 4.7.0

Installed Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/ios: 4.6.3

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by axi** [comment]
![image](https://user-images.githubusercontent.com/389340/225065987-bd91e00d-b485-44db-9db8-1303131e231c.png)

**Comment by robingenz** [comment]
Thanks for reporting this!

Unfortunately, I can't reproduce it with the [demo app](https://github.com/robingenz/capacitor-plugin-demo) on my iPhone with iOS 16. 

Please share the following information with me:
- XCode Version
- iOS Version
- Whether you can reproduce it in the simulator or not

**Comment by axi** [comment]
Xcode Version 13.4.1 <= that's probably the problem 😅
I would have thought that the ```if #available(iOS 16, *)``` would have also be understood by the compiler: "you don't know about iOS 16, let's forget about this if".
I'll update xcode and reopen if still having the problem. Sorry about the troubles.
